"""Compare molecular dynamics histograms across multiple BAM runs.

Reads per-run histogram CSVs (generated by ``md_analysis raw-bam``), groups them
by type (total_hist / total_per_base_hist), and plots overlayed bar-chart histograms
so different runs can be compared visually.

Usage::

    raw-bam-analysis --bams run1.bam run2.bam run3.bam --outdir ./output/

Accepts BAM files, CSV files, or directories containing BAMs (auto-detected by
extension). When a BAM path is given and its expected CSV files do not yet exist
in the same directory, ``md_analysis -i <bam> raw-bam`` is invoked automatically.
"""

import argparse
import logging
import os
import pathlib
import subprocess
import sys

import matplotlib

matplotlib.use("Agg")  # noqa: E402 – must be set before importing pyplot
import matplotlib.pyplot as plt  # noqa: E402

import polars as pl
import seaborn as sns

logging.basicConfig(
    level=logging.INFO,
    datefmt="%Y/%m/%d %H:%M:%S",
    format="%(asctime)s - %(levelname)s - %(message)s",
)
log = logging.getLogger(__name__)

# md_analysis slice_n=0 (default) output file suffixes
_TOTAL_SUFFIXES = (".total_hist.csv", ".total_per_base_hist.csv")
_SLICE_N_SUFFIXES = (
    ".first_n_total_hist.csv",
    ".last_n_total_hist.csv",
    ".first_n_per_base_hist.csv",
    ".last_n_per_base_hist.csv",
)


# --------------------------------------------------------------------------- #
#  CSV discovery
# --------------------------------------------------------------------------- #


def _csv_suffix(basename):
    """Return the recognised suffix (e.g. ``'.total_hist.csv'``) for a basename,
    or ``None`` if it does not match any known pattern."""
    for sfx in _TOTAL_SUFFIXES + _SLICE_N_SUFFIXES:
        if basename.endswith(sfx):
            return sfx
    return None


def _category_from_suffix(suffix):
    """Map a file suffix to the canonical category label.

    First_n / last_n variants collapse into total / per_base_hist so they
    are plotted together rather than producing separate overlay figures.
    """
    name = suffix[1:-4]  # e.g. "first_n_total_hist"
    if "per_base_hist" in name:
        return "total_per_base_hist"
    if "total_hist" in name:
        return "total_hist"
    return name


def _run_md_analysis(bam_path):
    """Run ``md_analysis -i <bam> raw-bam`` (same directory for output)."""
    log.info("Running md_analysis on %s", bam_path)
    subprocess.check_call(["md_analysis", "-i", bam_path, "raw-bam"])


def _discover_csv_for_bam(bam_path):
    """For a single BAM file, find (or generate) its CSV files.

    Returns ``{category_label: csv_path}``.

    Checks both total_hist suffixes and slice_n variants (first_n/last_n).
    md_analysis only produces one set per BAM, so there is no duplicate risk.
    """
    stem = pathlib.Path(bam_path).stem
    csv_dir = pathlib.Path(bam_path).parent
    found = {}

    for sfx in _TOTAL_SUFFIXES + _SLICE_N_SUFFIXES:
        expected = csv_dir / (stem + sfx)
        if expected.exists():
            cat = _category_from_suffix(sfx)
            found[cat] = expected
            log.info("Found CSV %s", expected)

    # If neither total nor slice_n CSVs exist, run md_analysis to generate them
    if not found:
        log.info("No default CSVs for %s, running md_analysis ...", stem)
        _run_md_analysis(bam_path)
        for sfx in _TOTAL_SUFFIXES + _SLICE_N_SUFFIXES:
            expected = csv_dir / (stem + sfx)
            if expected.exists():
                cat = _category_from_suffix(sfx)
                found[cat] = expected

    return found


def discover_csvs(inputs):
    """Discover histogram CSVs from a mix of BAM/CSV/dir inputs.

    Returns ``{category: {run_label: csv_path}}`` where *run_label* is the
    stem derived from the input file name (shortened if long).
    """
    # category -> run_label -> csv_path
    groups = {}

    for inp in inputs:
        p = pathlib.Path(inp)
        label = p.stem
        if len(label) > 30:
            label = label[:27] + "..."

        if p.suffix.lower() == ".bam":
            csv_map = _discover_csv_for_bam(str(p))
            for cat, csv_path in csv_map.items():
                groups.setdefault(cat, {})[label] = csv_path

        elif p.suffix.lower() == ".csv":
            sfx = _csv_suffix(p.name)
            if sfx is None:
                log.warning("Unrecognised CSV filename, skipping: %s", p)
                continue
            cat = _category_from_suffix(sfx)
            groups.setdefault(cat, {})[label] = p

        elif p.is_dir():
            # glob *.bam inside the directory
            for bam in sorted(p.glob("*.bam")):
                csv_map = _discover_csv_for_bam(str(bam))
                # prefix label with dir name to avoid collisions
                dir_label = p.name + "_" + bam.stem[:20]
                if len(dir_label) > 30:
                    dir_label = dir_label[:27] + "..."
                for cat, csv_path in csv_map.items():
                    groups.setdefault(cat, {})[dir_label] = csv_path

    return groups


# --------------------------------------------------------------------------- #
#  Plotting
# --------------------------------------------------------------------------- #


def _plot_overlay_on_ax(ax, csv_groups, column, bin_clip):
    """Draw overlayed histogram bars on *ax* for all runs in *csv_groups*.

    Every 5 consecutive bins are summed into one bucket, then each run's per-bucket
    counts are normalised to a proportion (sum-to-1) within that run before drawing.
    Bars for each run are dodged (side-by-side) around each bucket centre.
    """
    n_runs = len(csv_groups)
    bar_width = 5 * 0.6 / max(n_runs, 1)
    palette = sns.color_palette("deep", n_runs)

    for idx, run_label in enumerate(sorted(csv_groups.keys())):
        df = pl.read_csv(csv_groups[run_label], separator=",").filter(
            pl.col("bin_idx") < pl.lit(bin_clip))
        # sum every 5 consecutive bins into one bucket
        binned = df.with_columns(
            (pl.col("bin_idx") // 5 * 5).alias("binned_idx"))
        agg = binned.group_by("binned_idx").agg(
            pl.col(column).cast(pl.Float64).sum().alias(column)
        ).sort("binned_idx")
        # normalise to proportion within this run
        total = int(agg[column].sum())
        if total > 0:
            agg = agg.with_columns(
                (pl.col(column) / total).alias(column))
        centers = agg["binned_idx"].to_numpy() + (idx - n_runs / 2.0 + 0.5) * bar_width
        ax.bar(
            centers,
            agg[column].to_numpy(),
            width=bar_width,
            label=run_label,
            color=palette[idx],
            alpha=0.85,
            edgecolor="none",
        )


def _plot_for_column(csv_groups, column, outpath):
    """Plot *column* (dw or ar) as overlayed histogram bars across all runs."""
    fig, ax = plt.subplots(figsize=(10, 5))
    CLIP_MAX = 500

    _plot_overlay_on_ax(ax, csv_groups, column, CLIP_MAX)

    # x-axis ticks every 25 bins (5 original-bins * 5 buckets shown as major ticks)
    tick_vals = list(range(0, CLIP_MAX, 25))
    ax.set_xticks(tick_vals)
    ax.set_xticklabels([str(t) for t in tick_vals], fontsize=7)

    ax.set_xlabel("bin_idx")
    ax.set_ylabel(column)
    ax.set_title("{} distribution across runs".format(column))
    ax.legend(loc="upper right", fontsize=8)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(outpath, dpi=300)
    plt.close(fig)
    log.info("Saved %s", outpath)


def _plot_per_base_for_column(csv_groups, column, outdir):
    """For *total_per_base_hist*, plot A/C/G/T distributions on a 2x2 grid for *column*.

    Each subplot shows overlayed histogram bars (dw or ar) for one base across all runs.
    Data is pre-aggregated to avoid repeated CSV reads per subplot.
    """
    # detect available bases from the first CSV
    sample_csv = next(iter(csv_groups.values()))
    base_series = pl.read_csv(sample_csv, separator=",")["base"].unique()
    bases = sorted(base_series.to_list())  # A, C, G, T

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.ravel()
    bin_clip = 500

    for i, base in enumerate(bases):
        ax = axes[i]
        if i >= len(bases):
            ax.axis("off")
            continue

        # pre-aggregate per-base data for each run to avoid repeated CSV reads
        run_data = {}
        for label, path in csv_groups.items():
            df = pl.read_csv(path, separator=",").filter(
                pl.col("base") == base, pl.col("bin_idx") < pl.lit(bin_clip))
            if len(df) > 0:
                binned = df.with_columns(
                    (pl.col("bin_idx") // 5 * 5).alias("binned_idx"))
                agg = binned.group_by("binned_idx").agg(
                    pl.col(column).cast(pl.Float64).sum().alias(column)
                ).sort("binned_idx")
                total = int(agg[column].sum())
                if total > 0:
                    agg = agg.with_columns((pl.col(column) / total).alias(column))
                run_data[label] = agg

        n_runs = len(run_data)
        if n_runs < 2:
            ax.text(0.5, 0.5, "insufficient data ({} runs)".format(n_runs),
                    transform=ax.transAxes, ha="center", va="center")
            continue

        palette = sns.color_palette("deep", n_runs)
        bar_width = 5 * 0.6 / max(n_runs, 1)

        for idx, run_label in enumerate(sorted(run_data.keys())):
            agg = run_data[run_label]
            centers = agg["binned_idx"].to_numpy() + (idx - n_runs / 2.0 + 0.5) * bar_width
            ax.bar(centers, agg[column].to_numpy(), width=bar_width,
                   label=run_label, color=palette[idx], alpha=0.85, edgecolor="none")

        tick_vals = list(range(0, bin_clip, 25))
        ax.set_xticks(tick_vals)
        ax.set_xticklabels([str(t) for t in tick_vals], fontsize=7)
        ax.set_xlabel("bin_idx")
        ax.set_ylabel("proportion")
        ax.set_title("base = '{}'".format(base))
        ax.legend(loc="upper right", fontsize=7)
        ax.grid(True, alpha=0.3)

    plt.tight_layout()
    outpath = os.path.join(outdir, "total_per_base_hist_{}_comparison.png".format(column))
    fig.savefig(outpath, dpi=300)
    plt.close(fig)
    log.info("Saved %s", outpath)


def plot_by_category(csv_groups, outdir):
    """For every category, produce comparison figures.

    Returns list of produced file paths.
    """
    os.makedirs(outdir, exist_ok=True)
    produced = []

    for category in sorted(csv_groups.keys()):
        run_map = csv_groups[category]
        if len(run_map) < 2:
            log.warning(
                "Category '%s' has only %d run(s) -- skipping overlay plot.",
                category, len(run_map),
            )
            continue

        # total_per_base_hist gets two 2x2 figures (A/C/G/T subplots for dw and ar)
        if category == "total_per_base_hist":
            for col in ("dw", "ar"):
                _plot_per_base_for_column(run_map, col, outdir)
                produced.append(os.path.join(
                    outdir, "total_per_base_hist_{}_comparison.png".format(col)))
            continue

        for col in ("dw", "ar"):
            # Validate all CSVs have the same column schema
            sample_csv = next(iter(run_map.values()))
            sample_df = pl.read_csv(sample_csv, separator=",")
            sample_df = sample_df.filter(pl.col("bin_idx") < pl.lit(1000))

            if col not in sample_df.columns:
                log.warning(
                    "Column '%s' missing in %s -- skipping", col, category)
                continue

            outpath = os.path.join(
                outdir, "{}.{}_comparison.png".format(category, col))
            _plot_for_column(run_map, col, outpath)
            produced.append(outpath)

    return produced


# --------------------------------------------------------------------------- #
#  CLI entry point
# --------------------------------------------------------------------------- #


def main(args=None):
    """Main entry -- discover CSVs and produce overlayed plots."""
    if args is None:
        parser = _build_parser()
        args = parser.parse_args()

    groups = discover_csvs(args.bams)
    outdir = args.outdir or os.path.join(
        os.getcwd(), "raw_bam_analysis_output")

    produced = plot_by_category(groups, outdir)
    if produced:
        log.info("Done -- %d plot(s) written to %s", len(produced), outdir)
    else:
        log.warning("No plots generated (no matching CSV data found).")
    return produced


def _build_parser():
    parser = argparse.ArgumentParser(
        prog="raw-bam-analysis",
        description=(
            "Compare molecular dynamics histograms across multiple runs. "
            "Each run's per-bin dw/ar counts are overlayed on a single figure."
        ),
    )
    parser.add_argument(
        "--bams", nargs="+", required=True,
        help="BAM files, CSV files, or directories (auto-detected by extension)",
    )
    parser.add_argument(
        "--outdir", default=None,
        help="Output directory for plots (default: ./raw_bam_analysis_output/)",
    )
    return parser


def main_cli():
    args = _build_parser().parse_args()
    produced = main(args)
    if not produced:
        sys.exit(1)


if __name__ == "__main__":
    main_cli()
