#!/usr/bin/env python3
"""Convert hardcoded STR sequence data into a FASTA file.

The STR records (name + sequence) are embedded below. Running this script
writes them to ``str_sequences.fasta`` (current directory) with each sequence
kept on a single line (no 80-char wrapping).

Example:
    python str_seq_to_fasta.py
"""

import os
import sys

# One big string: comment lines are FASTA headers, following lines are sequence
STR_SEQUENCES = """
# STR-3N
CTGGCCTGATTGCTATTGTTAGCACTGCtagttctttgttgactagaagtggtgatagtggacatacttctttttatataaaattttaaaattttcttcttaatttcttccttgactcattggtcatgttgtttcatttccacatgtttgcatattttctaaggttcctcttgttattcatttgtagttttattcaactgtggtcagaaaagtcatttgatatgatttctattgttttaaaaatttgttgagtcttgttttgcagccaatatgtggtctattctagaagatgttccgtatgcccatgaaaataatgtgtgcatgtgtatatatataaaaaatataatatataatatatattaatatgtaataaataattatatatataatataatatatattatattatatatatagtatctacatatatatatacacacacacacacacatacataggatacagtgagagacataacatggctaaaagattaatgatgactaaaaggcccatgcaaacatcttgcagcatggacatattgtgtcacttagtcttgatcacaacactgagctaatcttaaaaggaaaaaagaagccttcaggaaaatacattttgatttctgagctgaaattactagacatttctagaattgtaaatggaagaattttttattctagtagaagagacattgacaaagccagggaaattctttaagtcagtatctgaattaatctgaattagactatctgtggtgggttgtactGGCTTGGTCTAGAACTGGCTTATAGGTG

#STR-4
ACATACATGTTAGACTCTGGCCCAGATAAGaagaaatctcattaacattttgcagacatagtttacaggatgactataagtaacatgaaaaatatgtgagtgtgttctatgctgtatcaggagagaaaaaaaattcaacttagaaactattgcttcaatggtttggtggaagttcacagtttagaatttcagctcagtaaattttgataatcagattaacattagtgtatatatacacatacatatatacatatatacatatattatatattaatatatgcatatataaataaatatacatacatagatatatatacatatcatatatatatatatttcctaacataactaagcttacagacttggtttgaacctcattgtatagaagcctatgcagtagcaataatatcctgaaattatttttattttaatacaagggatttggaatacttggcaaacattaagaccattaactatattttcagatgaagaaccaacaacaaaatgagatgacatggtgctagttattttaactactcaaagataaaagaaAGAATAGGCTATAGGCAGAGTCCACATAGC

#STR-5
TATATAGAGTGTGAGCGTATGTGTACACGCacacatacacacacacacacagagatatatatgtgtttgagctggacatgagaagctaacagcataattgggaatgaggggaaagataggttatagatattacctagactattaacaaacttaataggaacatttaacatttaatggtgtgtgtgtgtgtgtgtgtgtatatatatacatatataatatgtatatatataaaatatgtatatatgtatatatataaaatatgtatatataatatgtatatatatagtgtatcacgtatatatcatatatatgagatgtttctgctaatgtaatatatatactccaaaaagaattatgttctaaaatatctgacactgaacacaatagtgttccagagaaaaatagggttgagggcgatccatcaaaacttctgaaactttttattcagagtactaccataaataatagcatcttaaaaatattcaagcatagttaaaaaagaaacatgttaaatcctaaaaaaaaaaattattgaatataggactttatctttgggagaggaaaaagaaaggtagaacaagggaggacaatagggaatgactaaagctgcaaagttctggagatgagggcaaaatgtatttctaagagcacccggcctcactgaaccatgaggaagactggAGGTGAATCCAGTACCACGACCTTGACA

#STR-7
CAGATGGCCCTCTTCAAAGTAGTTAGGCAtccttcaatctgttgagggtttcaatgtaacaaaaatgtagaggaagattaaattcactctctccttgactacttgagctttatcataaatctcctcctgccctcagtgctctcaatcctcaggaggctttcagacttggactggaatccataccataagtgccctggctctcaggcatttgaactatactgcaggccttcctgaatctccagcttacagatgatagatcatgggacttctcagccttcataatcacatatcacatgagctaacacacacacacacacacacatgcatacatgcatgcacatacacataactagatagactgacagatagatagatagatagatagatagatagatagatagatagatagatagacagacagacagacagatagatattcattcccctggttctgtttccctggagagccctaatacaatggtgtgtgagagtccacacttcattcttttgcatgtggatatccaattttccctaccacaatttgttgcaaaggcaatccttggcaccctgtcaaaaatcatttaaCCATATAGGAAGGATTTATTTCTGGGTCCT

#STR12
TTAGTCCCTAGGGGACACTTGGTGATGTAtggagacatttttggtcatcatgactctggggtggagggtgtgcttctggtatctggttgctgcagccctgggatcctgctcaacatcctacagtgcacaagacaccccaccacagattagcattcatcttgccttaaatgttaatactgctgaggtcaagtaaccctgtcttagcatgtaagattttgtctgtccatttagctatctatttatccattcattcattcctgtatacctaacctatcatccatccttatctcttgtgtatctattcattcaatcatacacccatatctgtctgtctgtctatctatctatctatctatctatctatctatctatctatctatctgcctatctgcctgcctacctatccctctatggcaattgcttgcaaccagggagattttattcccaggagatatttggctatgtctgacaacaatttttttggttgtcacaaatgggatgaatgttactggcatctggtgggtggagcccagagatgctgctcaacaccctacagtgcacaagacagacccaccacaaaGAATCCTCCATACAGCCTTAAATGTCCCTA

#STR 25
AAGCATAGATATGGACTTACTAGACAACGCtttaaatcaacagtcttaaatgtgaacagagagctaaagaaaaacatggacaaggacaagtaactaaagaatatcaggaagaaatgtataaatagatgaagaacatcaataaaaggcaaccatatagaaatatagagttgaaaagtacaaatactgaataaaaactcactagaggggtccaacagaagagttgaactggcagaagaatcagaaaacaaaaagatagggtaattggattactcagtgaatagcagaaaagaattaagaaaaattaacaaatcataaagaacatgaagccatcaaatatatatataaatatattatatatatttatatataatatatttatatatatacatatatatgtgtatatatatacacatatatatgtatgtatatatatatatatataatcagaatcccaggaaaatagaataagtggtagaaagatcatttgaagaaataatgatcaaaactccccaaatttgatataaaatgtaaacctacacatgcacaaagctcaatgggctctaagtaggataaactcaaaggtccacatcaagacatatgataattaaattgtggaaagacagaaacagagagcatattttaaaaggagtaagagaaatagtgatttgtcatacacaattcattctCAATAACGTTAAGAGCCAATTTCTCACCTG

#STR27
AGGCTGGAGTGCAATGGCATTTTCACAATTctgcgcagccttgaactcctgggctcaagtgatccttccacttcagccttcccagcagctaagactacttcccagcagctgagactataggcacacaacaccatgactggatttatgtatatgtgtgtgtgtgtgtgtgtgtatatatacatatatatatatgtatgtatatatatatgtatatatacacacacacacatatatatatacacacacacacatatatacacacacacacacatatatatatatacacatacacacacacacacacacacacagacacacacacatacatatataggcaagatcccactatgttgcccaggctggctgcaaactcctgggctcaagcaatctctctttctggccttggcctcccaaagtgctgggattacaggtgtgatccagcatgcccagccaataaaaatattttcagaattaccaccaaacagttttattggtactctccaatttagggcatcccattaTTGAGATTAGGTGAATTGGTCAGGCTCACC

#STR28
AAGGGTTGTCTCAGTTTGTACTCCCTAACCcacctacctccttccctgccagcaatgttagagaagatgtttcagtcacagatcacctgcacaggcagaatcacttttaaattatgttccaatttgatgatcaacaaatggcgtctcatttcaaattgcatttttaatattgagcttaatttttaagagtttacagatcaaatcattttcttttcttttttgtcaactatcagtccatgccatttgcctgtttttttattggtatgttttatcatttaaaattttatctgcaagaggtatatatatatatatatgtctgtatatatgtgtatatatgtgtatatatatatctgtatacatgtatatatatctgtatatacatgtatatatatctgtgtatatatatgtatgtatacacacacacacacacacacacacacacacatatatatatatacacacacattaaggatttagggcttcttcacccaaactgctctccaatacccaaaagcataatacccctccttgtattgtccctaaaggggggtattattattgtcacacttattttatagattaaaaaaccttggacacaaagaagttaagcattttgcaaaatgtcagtatcaaataaGTGATAGAGGTTGAAGAGTTGCTTTTAACC

#STR29
TCCGTGTAGTATTCCATTGTATGAATGTGCcatagtatgtttaaccattcacctattgagtgacatttgggatatttctagtgttgggttattatgaataatgctgtcatgaacattgatgtgcaggtttagtgtcgacataggttttttttcctctgggataaatgcacaaaagaacaattgtcaggtcataaggtaagtagcgtttagtcttaggagaaactgacaacctattactactactactactattactactactactacttcttcttcttcttcttcttcttcttcttcttcttcttcttcttcttctttcttttttctttcttctttcttccttcttctttcttctttcttccttcttcctttttcttccttttttttttttttttttttcagaatggggttttgagtgtttgggaggagtaccaaatccatgatgtgaagctatttgtagtttgttttagacatggatttgcctcctgctctgaaaacacattgtatagtggtcagttccttagctcttaagcaatgagtatccacatctcattgtgttttcagtattctCTAAAGTGACTCTTGCTTCCTTACTGAGGC

#STR33
ACAGAGAGAGACCCTGACAGGAAAGGAAgaaagaaagaaggaaagaaggaaaggaagaaagaaagaaggaaagaaggaaagaaaaagaaagaaggaaagaaagaaagaaagaaagaaagaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaaggggaagggaagggaaggaaggagagagggagagagagagaggaagggaagggaagagaggaagggaagggaggaaggaaggaaaggagagagagagagtgaaagacagagagagagaggagagagagagagaaagagagagaggagagagagaaagagaaagagagaggagagagacagcaagagagaaagagaaaaaggaagggaaagaaagagaaacgaaagcaaagaaaagaaagagagcccaatgatgggatttcaccatgttggccaggctggtcttgaactcctgacttcaggtgatcctccctctttggtctcccaaagtgctgggattacaggcatgagccaccacacccagccaacattttcttaaatagtcatccattagtcaaatatccaaatgggacaaactttaaatatgtatgtttgtcaatgaatatcttaattcatttgtgttacgtattaaggatttgtttatttttagaaaatttcagtgtttaggaaaaaatgcgttattaaataagtttggcctttgtttaagtctattcatttataaatagtatattcataaatgtactttattagaaatatttgtaaacctgtgagatcttttttcttattcttttgccaactttcaaaaatagttttactttcataagtagaaaagcttagtcatattatattttcctctcttcttctacacctagcagaaattgactttatttttctgactccatttaaataataatctctcctccatttttcttcaaaataaagtcatcatagaaaatgggaagatgaaGCCATGGTCCTAAAGCACAGTCTCTGAA

#STR38
GGAGATAAAGATGCCTACATATCCGCGATGttaagaagattaatttagatgaaatacataaagtggctagcattccatgttagatttcttccttatctgtagaatggggtaataatacctgacaataatataatcctacttatccatagcctactaagggctctgtggaaggctgcaaggattgaatatacctgaattcttctaaaaatgtctgatttggaggttaaaacttctgaaagatgatgtcaccgaaacacgagtaagaactacatcaggctttcctagaatgtgtccttttggaaccaagagacagtgaattatgaaagaattctgaaatcagatatgtttgggaaattctgctgtctctttctatatatatatatatatatatatatatgtatatgtgtgtgtgtatatatatatatgtatatatatgtgtatatatatatatttttttccccagtcctcagaactgaaattcttggatcacaaacctgacagctttcatatttgtgaagctttttacccagcccttgttgaccttactgctcacatatgactagggtatttaggaaggaagtaggcagaaatccttcatCGGCTGTTCACATGAATATTCTTCACTAGC
"""


OUT_PATH = "str_2rd_str_sequences.fasta"


def main() -> int:
    """Write the hardcoded STR sequences to a FASTA file.

    Returns
    -------
    int
        0 on success, 1 on error.
    """
    records = []  # list of (header, sequence)
    cur_header = None
    cur_seq = []

    for line in STR_SEQUENCES.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            if cur_header is not None:
                records.append((cur_header, "".join(cur_seq)))
            cur_header = stripped.lstrip("#").strip()
            cur_seq = []
        elif stripped and cur_header is not None:
            cur_seq.append(stripped)

    if cur_header is not None:
        records.append((cur_header, "".join(cur_seq)))

    if not records:
        print("Error: no STR records defined.", file=sys.stderr)
        return 1

    with open(OUT_PATH, "w", encoding="utf8") as fout:
        for header, seq in records:
            
            seq = seq.upper()
            fout.write(f">{header}\n{seq}\n")

    print(f"Wrote {len(records)} sequences to {os.path.abspath(OUT_PATH)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
