#!/usr/bin/env python3
"""Write STR reference sequences to a FASTA file."""

import argparse

STR_ENTRIES = [
    ("STR_3N",
        "CTGGCCTGATTGCTATTGTTAGCACTGCtagttctttgttgactagaagtggtgatagtggacatacttctttttatataaaattttaaaattttcttcttaatttcttccttgactcattggtcatgttgtttcatttccacatgtttgcatattttctaaggttcctcttgttattcatttgtagttttattcaactgtggtcagaaaagtcatttgatatgatttctattgttttaaaaatttgttgagtcttgttttgcagccaatatgtggtctattctagaagatgttccgtatgcccatgaaaataatgtgtgcatgtgtatatatataaaaaatataatatataatatatattaatatgtaataaataattatatatataatataatatatattatattatatatatagtatctacatatatatatacacacacacacacacatacataggatacagtgagagacataacatggctaaaagattaatgatgactaaaaggcccatgcaaacatcttgcagcatggacatattgtgtcacttagtcttgatcacaacactgagctaatcttaaaaggaaaaaagaagccttcaggaaaatacattttgatttctgagctgaaattactagacatttctagaattgtaaatggaagaattttttattctagtagaagagacattgacaaagccagggaaattctttaagtcagtatctgaattaatctgaattagactatctgtggtgggttgtactGGCTTGGTCTAGAACTGGCTTATAGGTG"
     ),
    ("STR4",
        "ACATACATGTTAGACTCTGGCCCAGATAAGaagaaatctcattaacattttgcagacatagtttacaggatgactataagtaacatgaaaaatatgtgagtgtgttctatgctgtatcaggagagaaaaaaaattcaacttagaaactattgcttcaatggtttggtggaagttcacagtttagaatttcagctcagtaaattttgataatcagattaacattagtgtatatatacacatacatatatacatatatacatatattatatattaatatatgcatatataaataaatatacatacatagatatatatacatatcatatatatatatatttcctaacataactaagcttacagacttggtttgaacctcattgtatagaagcctatgcagtagcaataatatcctgaaattatttttattttaatacaagggatttggaatacttggcaaacattaagaccattaactatattttcagatgaagaaccaacaacaaaatgagatgacatggtgctagttattttaactactcaaagataaaagaaAGAATAGGCTATAGGCAGAGTCCACATAGC"
     ),
    ("STR5",
        "TATATAGAGTGTGAGCGTATGTGTACACGCacacatacacacacacacacagagatatatatgtgtttgagctggacatgagaagctaacagcataattgggaatgaggggaaagataggttatagatattacctagactattaacaaacttaataggaacatttaacatttaatggtgtgtgtgtgtgtgtgtgtgtatatatatacatatataatatgtatatatataaaatatgtatatatgtatatatataaaatatgtatatataatatgtatatatatagtgtatcacgtatatatcatatatatgagatgtttctgctaatgtaatatatatactccaaaaagaattatgttctaaaatatctgacactgaacacaatagtgttccagagaaaaatagggttgagggcgatccatcaaaacttctgaaactttttattcagagtactaccataaataatagcatcttaaaaatattcaagcatagttaaaaaagaaacatgttaaatcctaaaaaaaaaaattattgaatataggactttatctttgggagaggaaaaagaaaggtagaacaagggaggacaatagggaatgactaaagctgcaaagttctggagatgagggcaaaatgtatttctaagagcacccggcctcactgaaccatgaggaagactggAGGTGAATCCAGTACCACGACCTTGACA"
     ),
    ("STR7",
        "CAGATGGCCCTCTTCAAAGTAGTTAGGCAtccttcaatctgttgagggtttcaatgtaacaaaaatgtagaggaagattaaattcactctctccttgactacttgagctttatcataaatctcctcctgccctcagtgctctcaatcctcaggaggctttcagacttggactggaatccataccataagtgccctggctctcaggcatttgaactatactgcaggccttcctgaatctccagcttacagatgatagatcatgggacttctcagccttcataatcacatatcacatgagctaacacacacacacacacacacatgcatacatgcatgcacatacacataactagatagactgacagatagatagatagatagatagatagatagatagatagatagatagatagacagacagacagacagatagatattcattcccctggttctgtttccctggagagccctaatacaatggtgtgtgagagtccacacttcattcttttgcatgtggatatccaattttccctaccacaatttgttgcaaaggcaatccttggcaccctgtcaaaaatcatttaaCCATATAGGAAGGATTTATTTCTGGGTCCT"
     ),
    ("STR12",
        "TTAGTCCCTAGGGGACACTTGGTGATGTAtggagacatttttggtcatcatgactctggggtggagggtgtgcttctggtatctggttgctgcagccctgggatcctgctcaacatcctacagtgcacaagacaccccaccacagattagcattcatcttgccttaaatgttaatactgctgaggtcaagtaaccctgtcttagcatgtaagattttgtctgtccatttagctatctatttatccattcattcattcctgtatacctaacctatcatccatccttatctcttgtgtatctattcattcaatcatacacccatatctgtctgtctgtctatctatctatctatctatctatctatctatctatctatctatctgcctatctgcctgcctacctatccctctatggcaattgcttgcaaccagggagattttattcccaggagatatttggctatgtctgacaacaatttttttggttgtcacaaatgggatgaatgttactggcatctggtgggtggagcccagagatgctgctcaacaccctacagtgcacaagacagacccaccacaaaGAATCCTCCATACAGCCTTAAATGTCCCTA"
     ),
    ("STR25",
        "AAGCATAGATATGGACTTACTAGACAACGCtttaaatcaacagtcttaaatgtgaacagagagctaaagaaaaacatggacaaggacaagtaactaaagaatatcaggaagaaatgtataaatagatgaagaacatcaataaaaggcaaccatatagaaatatagagttgaaaagtacaaatactgaataaaaactcactagaggggtccaacagaagagttgaactggcagaagaatcagaaaacaaaaagatagggtaattggattactcagtgaatagcagaaaagaattaagaaaaattaacaaatcataaagaacatgaagccatcaaatatatatataaatatattatatatatttatatataatatatttatatatatacatatatatgtgtatatatatacacatatatatgtatgtatatatatatatatataatcagaatcccaggaaaatagaataagtggtagaaagatcatttgaagaaataatgatcaaaactccccaaatttgatataaaatgtaaacctacacatgcacaaagctcaatgggctctaagtaggataaactcaaaggtccacatcaagacatatgataattaaattgtggaaagacagaaacagagagcatattttaaaaggagtaagagaaatagtgatttgtcatacacaattcattctCAATAACGTTAAGAGCCAATTTCTCACCTG"
     ),
    ("STR27",
        "AGGCTGGAGTGCAATGGCATTTTCACAATTctgcgcagccttgaactcctgggctcaagtgatccttccacttcagccttcccagcagctaagactacttcccagcagctgagactataggcacacaacaccatgactggatttatgtatatgtgtgtgtgtgtgtgtgtgtatatatacatatatatatatgtatgtatatatatatgtatatatacacacacacacatatatatatacacacacacacatatatacacacacacacacatatatatatatacacatacacacacacacacacacacacagacacacacacatacatatataggcaagatcccactatgttgcccaggctggctgcaaactcctgggctcaagcaatctctctttctggccttggcctcccaaagtgctgggattacaggtgtgatccagcatgcccagccaataaaaatattttcagaattaccaccaaacagttttattggtactctccaatttagggcatcccattaTTGAGATTAGGTGAATTGGTCAGGCTCACC"
     ),
    ("STR28",
        "AAGGGTTGTCTCAGTTTGTACTCCCTAACCcacctacctccttccctgccagcaatgttagagaagatgtttcagtcacagatcacctgcacaggcagaatcacttttaaattatgttccaatttgatgatcaacaaatggcgtctcatttcaaattgcatttttaatattgagcttaatttttaagagtttacagatcaaatcattttcttttcttttttgtcaactatcagtccatgccatttgcctgtttttttattggtatgttttatcatttaaaattttatctgcaagaggtatatatatatatatatgtctgtatatatgtgtatatatgtgtatatatatatctgtatacatgtatatatatctgtatatacatgtatatatatctgtgtatatatatgtatgtatacacacacacacacacacacacacacacacatatatatatatacacacacattaaggatttagggcttcttcacccaaactgctctccaatacccaaaagcataatacccctccttgtattgtccctaaaggggggtattattattgtcacacttattttatagattaaaaaaccttggacacaaagaagttaagcattttgcaaaatgtcagtatcaaataaGTGATAGAGGTTGAAGAGTTGCTTTTAACC"
     ),
    ("STR29",
        "TCCGTGTAGTATTCCATTGTATGAATGTGCcatagtatgtttaaccattcacctattgagtgacatttgggatatttctagtgttgggttattatgaataatgctgtcatgaacattgatgtgcaggtttagtgtcgacataggttttttttcctctgggataaatgcacaaaagaacaattgtcaggtcataaggtaagtagcgtttagtcttaggagaaactgacaacctattactactactactactattactactactactacttcttcttcttcttcttcttcttcttcttcttcttcttcttcttcttctttcttttttctttcttctttcttccttcttctttcttctttcttccttcttcctttttcttccttttttttttttttttttttcagaatggggttttgagtgtttgggaggagtaccaaatccatgatgtgaagctatttgtagtttgttttagacatggatttgcctcctgctctgaaaacacattgtatagtggtcagttccttagctcttaagcaatgagtatccacatctcattgtgttttcagtattctCTAAAGTGACTCTTGCTTCCTTACTGAGGC"
     ),
    ("STR33",
        "ACAGAGAGAGACCCTGACAGGAAAGGAAgaaagaaagaaggaaagaaggaaaggaagaaagaaagaaggaaagaaggaaagaaaaagaaagaaggaaagaaagaaagaaagaaagaaagaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaagaaaggggaagggaagggaaggaaggagagagggagagagagagaggaagggaagggaagagaggaagggaagggaggaaggaaggaaaggagagagagagagtgaaagacagagagagagaggagagagagagagaaagagagagaggagagagagaaagagaaagagagaggagagagacagcaagagagaaagagaaaaaggaagggaaagaaagagaaacgaaagcaaagaaaagaaagagagcccaatgatgggatttcaccatgttggccaggctggtcttgaactcctgacttcaggtgatcctccctctttggtctcccaaagtgctgggattacaggcatgagccaccacacccagccaacattttcttaaatagtcatccattagtcaaatatccaaatgggacaaactttaaatatgtatgtttgtcaatgaatatcttaattcatttgtgttacgtattaaggatttgtttatttttagaaaatttcagtgtttaggaaaaaatgcgttattaaataagtttggcctttgtttaagtctattcatttataaatagtatattcataaatgtactttattagaaatatttgtaaacctgtgagatcttttttcttattcttttgccaactttcaaaaatagttttactttcataagtagaaaagcttagtcatattatattttcctctcttcttctacacctagcagaaattgactttatttttctgactccatttaaataataatctctcctccatttttcttcaaaataaagtcatcatagaaaatgggaagatgaaGCCATGGTCCTAAAGCACAGTCTCTGAA"
     ),
    ("STR38",
        "GGAGATAAAGATGCCTACATATCCGCGATGttaagaagattaatttagatgaaatacataaagtggctagcattccatgttagatttcttccttatctgtagaatggggtaataatacctgacaataatataatcctacttatccatagcctactaagggctctgtggaaggctgcaaggattgaatatacctgaattcttctaaaaatgtctgatttggaggttaaaacttctgaaagatgatgtcaccgaaacacgagtaagaactacatcaggctttcctagaatgtgtccttttggaaccaagagacagtgaattatgaaagaattctgaaatcagatatgtttgggaaattctgctgtctctttctatatatatatatatatatatatatatgtatatgtgtgtgtgtatatatatatatgtatatatatgtgtatatatatatatttttttccccagtcctcagaactgaaattcttggatcacaaacctgacagctttcatatttgtgaagctttttacccagcccttgttgaccttactgctcacatatgactagggtatttaggaaggaagtaggcagaaatccttcatCGGCTGTTCACATGAATATTCTTCACTAGC"
     ),
]


def write_fasta(entries, output_path):
    with open(output_path, "w") as fh:
        for name, seq in entries:
            fh.write(f">{name}\n")
            fh.write(seq.upper() + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Write STR reference sequences to a FASTA file."
    )
    parser.add_argument(
        "-o",
        "--output",
        default="str_sequences.fasta",
        help="Output FASTA file path (default: str_sequences.fasta)",
    )
    args = parser.parse_args()

    print(f"Writing {len(STR_ENTRIES)} STR sequences to {args.output} ...")
    write_fasta(STR_ENTRIES, args.output)
    total_bp = sum(len(seq) for _, seq in STR_ENTRIES)
    avg_len = total_bp / len(STR_ENTRIES)
    print(
        f"Done: {len(STR_ENTRIES)} entries, "
        f"{total_bp} total bp (avg {avg_len:.0f} bp/entry)."
    )
